---
    - shell:
        cmd: date +%H:%M
      register: time

    - name: Set directory variables
      set_fact:
        backup_directory: "{{ playbook_dir }}/checks/backup_directory"
        config: "{{ playbook_dir }}/roles/ipv6/config"

    - name: Create directory to store back up configuration
      file: 
        path: "{{ backup_directory }}"
        state: directory

    - name: Check files are present
      stat:
        path: "{{ role_path }}/config/{{ inventory_hostname }}/{{ item.key }}_{{ item.value }}.txt"
      with_dict:
      1: vrf
      2: interface
      3: prefix
      4: bgp
      5: ospf

    - name: Copying Running Configuration
      cli_command:
       command: show running-config
      register: pre_running_conf
    - copy:
       content: "{{ pre_running_conf.stdout[0] }}"
       dest: "{{ backup_directory }}/{{ time }}_{{ inventory_hostname }}_pre_running_config.txt"

    - name: Check IPv6 VRF config doesn't exist
      cli_command:
        command: "show vrf ipv6"
      register: vrf
    - assert:
        that:
          - "'' in item.stdout"
        success_msg: "No VRF Configuration exists. Continue"
        fail_msg: "Configuration already in place"
      with_items:
        - "{{ vrf.results }}"
      ignore_errors: True

    - name: Deploy VRF Configuration
      cli_config:
        config: "{{ lookup('file', '{{ config }}/{{ inventory_hostname }}/1_vrf.txt') }}"
        commit: yes

    - name: Check VRF Config
      cli_command:
        command: "show vrf ipv6"
      register: vrf_post
    - assert:
        that:
          - "'BBONEDEFAULT' in item.stdout"
        success_msg: "VRF Configuration exists. Continue"
        fail_msg: "Configuration not deployed"
      with_items:
        - "{{ vrf_post.results }}"
      ignore_errors: True

    - set_fact:
        po_list: |
          {%- set list = [] -%}
          {%- for interface in sites[inventory_hostname[0:3]][inventory_hostname[3:8]]['interfaces'] -%}
          {% if interface.startswith('po') %}
          {{ list.append(interface.strip('\n'))}}
          {%- endif -%}
          {%- endfor -%}
          {{ list }}

    - set_fact:
        lo_list: |
          {%- set list = [] -%}
          {%- for interface in sites[inventory_hostname[0:3]][inventory_hostname[3:8]]['interfaces'] -%}
          {% if interface.startswith('lo') %}
          {{ list.append(interface.strip('\n'))}}
          {%- endif -%}
          {%- endfor -%}
          {{ list }}
        
    - name: Pre-check Looback interface configuration
      cli_command:
        command: "show run interface {{ item }}"
      with_items:
        - "{{lo_list}}"
      register: lo_pre
    - assert:
        that:
          - "'ipv6 address' not in item.stdout"
          - "'ospfv3 1100 ipv6 area 0.0.0.0' not in item.stdout"
        success_msg: "No IPv6 configuration deployed on Loopback. Continue"
        fail_msg: "IPv6 configuration already deployed"
      with_items: 
        - "{{ lo_pre.results }}"
      ignore_errors: True

    - name: Pre-check port-channel interface configuration
      cli_command:
        command: "show run interface {{ item }}"
      with_items:
        - "{{po_list}}"
      register: po_pre
    - assert:
        that:
          - "'ipv6 address' not in item.stdout"
          - "'ipv6 nd ra suppress' not in item.stdout"
          - "'ospfv3 1100 ipv6 area 0.0.0.0' not in item.stdout"
          - "'ospfv3 cost 200' not in item.stdout"
        success_msg: "No IPv6 configuration deployed on Port-Channels. Continue"
        fail_msg: "IPv6 configuration already deployed on Port-Channels"
      with_items: 
        - "{{ po_pre.results }}"
      ignore_errors: True

    - name: Deploy Interface Configuration
      cli_config:
        config: "{{ lookup('file', '{{ config }}/{{ inventory_hostname }}/2_interface.txt') }}"
        commit: yes

    - name: Post-check Looback interface configuration
      cli_command:
        command: "show run interface {{ item }}"
      with_items:
        - "{{lo_list}}"
      register: lo_post
    - assert:
        that:
          - "'ipv6 address' in item.stdout"
          - "'ospfv3 1100 ipv6 area 0.0.0.0' in item.stdout"
        success_msg: "IPv6 configuration deployed on Loopback. Continue"
        fail_msg: "No IPv6 configuration deployed"
      with_items: 
        - "{{ lo_post.results }}"
      ignore_errors: True

    - name: Pre-check port-channel interface configuration
      cli_command:
        command: "show run interface {{ item }}"
      with_items:
        - "{{po_list}}"
      register: po_post
    - assert:
        that:
          - "'ipv6 address' in item.stdout"
          - "'ipv6 nd ra suppress' in item.stdout"
          - "'ospfv3 1100 ipv6 area 0.0.0.0' in item.stdout"
          - "'ospfv3 cost 200' in item.stdout"
        success_msg: "IPv6 configuration deployed on Port-Channels. Continue"
        fail_msg: "No IPv6 configuration deployed on Port-Channels"
      with_items: 
        - "{{ po_pre.results }}"
      ignore_errors: True

