---
    - name: Set directory variables
      set_fact:
        backup_directory: "{{ playbook_dir }}/checks/backup_directory"
        config: "{{ playbook_dir }}/roles/ipv6/config"

    - name: Create directory to store back up configuration
      file:
        path: "{{ backup_directory }}"
        state: directory

    - name: Copying Running Configuration
      cli_command:
       command: show running-config
      register: pre_running_conf
    - copy:
       content: "{{ pre_running_conf.stdout[0] }}"
       dest: "{{ backup_directory }}/{{ inventory_hostname }}_pre_running_config.txt"

    - set_fact:
        int_list: |
          {%- set list = [] -%}
          {%- for interface in sites[inventory_hostname[0:3]][inventory_hostname]['interfaces'] -%}
          {{ list.append(interface.strip('\n'))}}
          {%- endif -%}
          {%- endfor -%}
          {{ list }}

    - name: Pre-check interface configuration
      cli_command:
        command: "show run interface {{ item }}"
      with_items:
        - "{{int_list}}"
      register: int_pre
    - assert:
        that:
          - "'ipv6 address' not in item.stdout"
          - "'ipv6 nd suppress-ra' not in item.stdout"
        success_msg: "No IPv6 configuration deployed on Port-Channels. Continue"
        fail_msg: "IPv6 configuration already deployed on Port-Channels"
      with_items:
        - "{{ int_pre.results }}"
      ignore_errors: True

    - name: Deploy Interface Configuration
      cli_config:
        config: "{{ lookup('file', '{{ config }}/{{ inventory_hostname }}/1_interface.txt') }}"
        commit: yes

    - name: Pre-check interface configuration
      cli_command:
        command: "show run interface {{ item }}"
      with_items:
        - "{{int_list}}"
      register: int_post
    - assert:
        that:
          - "'ipv6 address' in item.stdout"
          - "'ipv6 nd suppress-ra' in item.stdout"
        success_msg: "IPv6 configuration deployed on Port-Channels. Continue"
        fail_msg: "No IPv6 configuration deployed on Port-Channels"
      with_items:
        - "{{ int_post.results }}"
      ignore_errors: True

    - name: Pre-check route-policy configuration
      cli_command:
        command: "show run {{ item }}"
      with_items:
        - "| i V6_BB1_LNS_OUTBOUND"
        - "| i V6_BB1_LNS_INBOUND"
      register: policy_pre

    - assert:
        that:
          - "'' in item.stdout"
        success_msg: "Route Policies not deployed. Continue"
        fail_msg: "Route Policies already deployed."
      with_items:
        - "{{ policy_pre.results }}"
      ignore_errors: True

    - name: Deploy Route policy Configuation
      cli_config:
        config: "{{ lookup('file', '{{ config }}/{{ inventory_hostname }}/2_route_policy.txt') }}"
        commit: yes

    - name: Pre-check route-policy configuration
      cli_command:
        command: "show run {{ item }}"
      with_items:
        - "| i V6_BB1_LNS_OUTBOUND"
        - "| i V6_BB1_LNS_INBOUND"
      register: policy_post

    - assert:
        that:
          - "'V6_BB1_LNS_OUTBOUND' in item.stdout"
          - "'V6_BB1_LNS_INBOUND' in item.stdout"
        success_msg: "Route Policies not deployed. Continue"
        fail_msg: "Route Policies already deployed."
      with_items:
        - "{{ policy_post.results }}"
      ignore_errors: True

    - name: Deploy BGP Configuation
      cli_config:
        config: "{{ lookup('file', '{{ config }}/{{ inventory_hostname }}/3_bgp.txt') }}"
        commit: yes

    - name: Copying Running Configuration
      cli_command:
       command: show running-config
      register: post_running_conf

    - copy:
       content: "{{ post_running_conf.stdout[0] }}"
       dest: "{{ backup_directory }}/{{ inventory_hostname }}_Post_Running_Config.txt"

