---
- name: Deploy ELN Config
  import_tasks: deploy_eln.yml
  tags: deploy_eln

- name: Deploy LAR Config
  import_tasks: deploy_lar.yml
  tags: deploy_lar

- name: Deploy SAR Config
  import_tasks: deploy_sar.yml
  tags: deploy_sar

