---

- name: Deploy DAS DNS Configuration
  hosts: "{{ hostname }}"
  connection: network_cli
  gather_facts: false
  vars_prompt:
    - name: hostname
      prompt: "Enter hostname"
      private: no
    - name: PW_Number
      prompt: "Enter PW Reference"
      private: no

  tasks:

    - name: set variables
      set_fact:
        backup_directory: "{{ playbook_dir }}/checks/backup_directory"
        config: "{{ playbook_dir }}/roles/dns/config"

    - name: Create directory to store back up configuration
      file: path={{ backup_directory }} state=directory

    - name: Copying Running Configuration on {{ inventory_hostname }} for {{ PW_Number }}
      cli_command:
       command: show running-config
      register: pre_running_conf
    - copy:
       content: "{{ pre_running_conf.stdout[0] }}"
       dest: "{{ backup_directory }}/{{ PW_Number }}_{{ inventory_hostname }}_Pre_Running_Config.txt"
   
    - name: Deploy DAS Configuration to {{ inventory_hostname }} for {{ PW_Number }}
      cli_config:
        config: "{{ lookup('file', '{{ config }}/{{ inventory_hostname }}/1_dns.txt') }}"
        commit: yes

    
 
