---

- name: Create directory for config
  file:
    path: "{{ role_path }}/config/{{ inventory_hostname }}/"
    state: directory
  tags: eln, lar, sar

- name: Generate ELN Config
  import_tasks: generate/eln.yml
  tags: eln

- name: Generate LAR Config
  import_tasks: generate/lar.yml
  tags: lar 

- name: Generate SAR Config
  import_tasks: generate/sar.yml
  tags: sar

- name: Deploy ELN 
  import_tasks: deployment/deploy_eln.yml
  tags: deploy_eln
