---
- name: Create directory for config
  file:
    path: "{{ role_path }}/config/{{ inventory_hostname }}/"
    state: directory
  tags: eln, lar, sar

- name: Generate ELN Config
  import_tasks: generate/eln.yml
  tags: eln

- name: Generate LAR Config
  import_tasks: generate/lar.yml
  tags: lar 

- name: Generate SAR Config
  import_tasks: generate/sar.yml
  tags: sar

- name: Assemble and generate device complete configuration
  assemble:
    src: "{{ role_path }}/config/{{inventory_hostname }}/"
    dest: "{{ role_path }}/config/{{ inventory_hostname }}/{{inventory_hostname }}_complete.conf"
    regexp: "_*.txt"
  tags: eln, lar, sar

- name: Deploy ELN 
  import_tasks: deployment/deploy_eln.yml
  tags: test

- name: Delpoy SAR
  import_tasks: deployment/deploy_sar.yml
  tags: deploy_sar 

- name: Deploy LAR
  import_tasks: deployment/deploy_lar.yml
  tags: deploy_lar
