- name: Generate SAR config
  template:
    src: "SAR/{{ item.value }}.j2"
    dest: "{{ role_path }}/config/{{ inventory_hostname }}/{{ item.key }}_{{ item.value }}.txt"
  with_dict:
    1: interfaces
    2: route_policy
    3: bgp

