- name: Generate some config
  template:
    src: "ELN/{{ item.value }}.j2"
    dest: "{{ role_path }}/config/{{ inventory_hostname }}/{{ item.key }}_{{ item.value }}.txt"
  with_dict:
    1: interface
    2: prefix
    3: ospf
