---
- name: Create directory for config
  file:
    path: "{{ role_path }}/config/{{ inventory_hostname }}/"
    state: directory
  tags: lar, eln

- name: Generate LAR Config
  import_tasks: lar.yml
  tags: lar

- name: Generate ELN Config
  import_tasks: eln.yml
  tags: eln
